# Generated by Django 5.2.8 on 2025-11-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('admin', 'Администратор'), ('student', 'Студент')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
