# Generated by Django 5.2.8 on 2025-11-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
